### PR TITLE
Adding pronouns to vitae package

### PR DESCRIPTION
**Pull request by isabelle-greco**
Adding pronouns to each template.

- [x] awesomecv
- [x] hyndman
- [x] latexcv
- [x] markdowncv
- [x] moderncv
- [x] twentyseconds

### CODE REVIEW

**Comment by isabelle-greco** [comment]
@mitchelloharawild I think this one is almost done. 

My only problem is with `moderncv`: I can't build the example even when pulling it from `main`. The error looks similar to #176: I suspect there is a 
```
\renewcommand*{\researchidsocialsymbol}{{\small\aiResearcherID}~} 
```
line somewhere that I can't find causing issues. Can you build the `moderncv` from main?

**Comment by mitchelloharawild** [comment]
I've fixed up the icon not showing on moderncv and I'm not encountering the issue you describe when building from `main`. Would you like to add yourself to the package contributors?

**Comment by isabelle-greco** [comment]
@mitchelloharawild I added the changes to `NEWS.md` as per `CONTRIBUTING.md` - is that what you meant? (sorry if I've misunderstood, I've never contributed to an R package before).

**Comment by mitchelloharawild** [comment]
> @mitchelloharawild I added the changes to `NEWS.md` as per `CONTRIBUTING.md` - is that what you meant? (sorry if I've misunderstood, I've never contributed to an R package before).

Great, thanks for adding the news entry. Even better that this is your first R package contribution!
The `DESCRIPTION` file contains some metadata about the package, including the authors (similar to a paper). To acknowledge your contributions to this package, you're welcome to add yourself as a contributor to the package there.

https://github.com/mitchelloharawild/vitae/blob/935d63d9863761bf5218530cf20e4aeece682599/DESCRIPTION#L4-L9

Fill in the information as best you can, for example:
```
person("Isabelle", "Greco", role="ctb")
```

You can also add your ORCID if you have one :+1:

**Comment by isabelle-greco** [comment]
@mitchelloharawild I think it's all done! Woo! Thanks for all your help with this one - I've definitely learned so much about R packages along the way.

**Comment by isabelle-greco** [comment]
@mitchelloharawild Just bumping this PR - no rush at all but just wanted to make sure it wasn't forgotten!

**Comment by isabelle-greco** [comment]
No rush at all @mitchelloharawild - I just want to make sure this PR isn't forgotten. Currently waiting on approval for the workflows.

**Comment by isabelle-greco** [comment]
Woo the workflows have passed! Are you happy to merge this PR @mitchelloharawild?

**Comment by isabelle-greco** [comment]
Just bumping again @mitchelloharawild, I'd hate for this work to get forgotten!

**Review by mitchelloharawild — APPROVED** [review]
Looks great to me, thanks for your contribution :tada:

**Pull request merged**
