### PR TITLE
Add ORCID support in for template awesome-cv

### PR DESCRIPTION
**Pull request by RLumSK**
I added support for ORCID in the awesome-cv template using the LaTeX package 'academicons'. 
I did not add news in NEWS.md and leave it to you.

### CODE REVIEW

**Comment by the-Hull** [comment]
👍  - was just about to do this and luckily saw your PR beforehand!

**Comment by mitchelloharawild** [comment]
@robjhyndman 
Do you know of a way to conditionally require this package when the `orcid` YAML input is used?

**Comment by robjhyndman** [comment]
Do you mean this?

```
$if(orcid)$
\usepackage{academicons}
$endif$
```

**Comment by mitchelloharawild** [comment]
Yes, although I didn't think that pandoc templating worked for *.cls files.

**Comment by robjhyndman** [comment]
This needs to go into the tex template, not the cls file.

**Comment by RLumSK** [comment]
@mitchelloharawild Two questions to make sure that I align with your aims and the package style:

1. Do you want to me to add Publons and Google Scholar on the top of this PR as I did it for the ORCID or do you want to have maybe a more general field that allows the user to insert LaTeX code directly instead of all these fields, for example: 

Instead of
```tex
$if(orcid)$
\orcid{$orcid$}
$endif$
```

We could add something like 

```tex
$if(social_media)$
$social_media$
$endif$
```

I know, this is risky and may lead to user errors, but so the users can add whatever they want in combination with the `academicons` package until you have the better implementation ready. 

2. From what I read above, I guess you prefer more `\usepackage` instead of a hard-coded dependency to 'academicons'.

**Comment by mitchelloharawild** [comment]
1. For now I think its best to use orcid (and other commonly requested social avenues) directly in the YAML header, and later on transition users to a more general and flexible interface such as `$social_media$`. Much like how `brief_entries()` and `detailed_entries()` work, I imagine that something similar can be done with `social_entries()`. By giving a function for socials I expect that it would be less error-prone than the current interface (and also more consistent with the vitae approach of being data driven - a list of socials is usually also maintained on a website for instance). 

2. My main apprehension with adding the academicons dependency is that not all users will need academic icons. While tinytex simplifies the LaTeX package management, many people still experience technical issues with this and requiring another less commonly used package could cause further problems.

So if it is possible to conditionally depend on this package that would be preferable, although if it is too much trouble I'm happy to accept the PR as is (even better with some other common socials from academicons).

**Comment by RLumSK** [comment]
I added the support as suggested, but only for the awesome-cv template. Let's see how it goes. 
The LaTeX package 'academicons' is no longer required. Although I don't know whether it will make a difference if it is not available (in terms of errors thrown by the LaTeX processor). 
I tested all three newly support social media accounts.

**Comment by mitchelloharawild** [comment]
Merged for upcoming release.
This interface of using the YAML header may change in the future for a more general approach to specifying these entries.

**Pull request merged**
