### PR TITLE
Added multiple-bibliographies.lua" filter

### PR DESCRIPTION
**Pull request by jooyoungseo**
# Breaking Changes

* Allowing users to print multiple bib files with preferable citation style using csl file (#52 and #87).
* Added myself (@jooyoungseo) to the author list as the third author as I think this commitment has made breaking changes and I have spent many hours; hopefully, it could be accepted.
* Used [multiple-bibliographies.lua](https://github.com/pandoc/lua-filters/tree/master/multiple-bibliographies).
* Made and arranged `inst/resources` directory by including lua-filter, some widely used csl files (apa6.csl; mla8.csl; acm.csl; ieee.csl; harvard-cite-them-right.csl; chicago17.csl), and the existing bib_format.tex files.
* Made some other required functions in `utils.R`.
* Modified the `cv_document.R` file to make the `vitae` package work with the "multiple-bibliographies.lua" filter.
* Added `academic` template to demonstrate the multiple bib-printing and explain its usage.

# Template

* A minimal usage can be found in the following template: 

``` r
rmarkdown::draft(
  "multi-bib-print-test",
  template = "academic",
  package = "vitae"
)
```

# Basic Usage

* I have copied and pasted the content of `academic` template to illustrate the detailed usage below:

````
---
name: Marie
surname: Curie
position: "Professor"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
csl: "`r vitae:::style('apa6.csl')`" # Replace 'apa6.csl' with your needs. Available options are: 'mla8.csl', 'acm.csl', 'ieee.csl', 'harvard-cite-them-right.csl', and 'chicago17.csl'.
# Or, you can put the "path/to/file.csl" above if you have your own csl file to customize.
nocite: "@*"  # Don't change this line if you want to print all the entries of your bib file(s).
bibliography_key1: "bib/journal.bib"  # Put anything unique for "key1" to remember; it should be matched with bib printing block later.
bibliography_key2: "bib/R-packages.bib"  # Likewise, put anything unique for "key2"; if more bib sections needed, make in the same way below.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
  "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
  "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

## Refereed Journal Papers

<!-- Notes: copy and paste the following block for any other bibliography sections with the same bibliography key matched that you assigned in YAML  -->
\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

::: {#refs_key1}
:::
\endgroup
<!-- Bib-printing block ends here. -->

## R Packages

```{r, cache = TRUE}
knitr::write_bib(c('ezpickr', 'mboxr', 'vitae'), "bib/R-packages.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

::: {#refs_key2}
:::
\endgroup
````

### CODE REVIEW

**Comment by mitchelloharawild** [comment]
Thanks for your efforts here.

I think it should be possible to implement this without introducing breaking changes.
In particular, the `bibliography_entries()` could set the required pandoc arguments with some `knitr` calls, and then the appropriate div code could be outputted in the location where `bibliography_entries()` was used.

I think the package doesn't need to re-distribute the CSL files. It would be better if users were to bring their own CSL (as they would for other rmarkdown output formats).

I'm also hopeful that the `bib_format.tex` file could be removed from the package if it is possible use pandoc for handling the bibliographies.

Let me know if you think you can make the above changes, I'm happy to help make changes if needed.

**Comment by jooyoungseo** [comment]
Thank you for the detailed feedback.
I will address those when I have more time.

The Travis CI gave me "fail," as I forgot to enclose my commit message with quotation mark. But, I don't think there is any functional errors.
I will address them later.

The csl files that I have packed there are some widely used csl but user still can replace the yaml if they have their own csl file. However, I will take that out if you think that distribution is unnecessary.

**Comment by mitchelloharawild** [comment]
Thanks again for looking into this.
Any chance you can get this done prior to the next release? I will need to submit to CRAN for breaking changes by the knitr package: https://github.com/mitchelloharawild/vitae/pull/91

Adding this to the package would be a great contribution and would be great to have in the next CRAN release.

**Comment by jooyoungseo** [comment]
It has been taking longer than what I expected.

I struggled with adding metadata required in YAML from `bibliography_entries()` function.
As far as I know, the typical way to interact with metadata is done either by pre- or post-processor when knitting a document.

As you see the example above, users have to provide bib files along with their unique IDs.

```yaml
bibliography_key1: "bib/journal.bib"  # Put anything unique for "key1" to remember; it should be matched with bib printing block later.
```

And, in the text body, you have to use the ID to print your entries:

```markup
::: {#refs_key1}
:::
```

I wanted to get `bibliography_entries()` to accept bib file argument along with its unique key-lable and to put the required metadata in YAML and insert the markup syntax where it is called for users without having to pre-define the bibliography metadata in the YAML.

Probably, I have to save the variable and post-process it in `cv_document`.

Any advice?

**Comment by mitchelloharawild** [comment]
Using `knitr` it should be possible to modify inputs to pandoc via knitr output types. Then with the bib file added to the pandoc inputs, the code can output the appropriate divs.

This may involve modifying the lua filter to make it more programmatic.

Looking into how vitae works with knitr to include the bibliography header tex code may help with finding knitr functions that control inputs to pandoc.

**Comment by mitchelloharawild** [comment]
Thanks for starting this thread on multiple bibliography lua filters. I've redone this to allow the current interface for `bibliography_entires()` to be maintained.

**Comment by jooyoungseo** [comment]
Thank you very much @mitchelloharawild!

I am very sorry; I should've done this earlier.....

**Pull request closed without merging**
